config/routes.rb
Student::Application.routes.draw do
  resources :course_subjects

  resources :chapters

  resources :subjects

  resources :syllabuses

  resources :courses

  root to: "home#index"

  devise_for :users, :controllers => { :registrations => "registrations" } do
    get "/login" => "sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  namespace :admin do
    resources :users do
      get 'all_courses',on: :collection
    end
  end

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Student" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js", "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/jquery-ui.min.js"%>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <% if user_signed_in? %>
              <a class="brand" href="#">Welcome <%= current_user.role%></a>
          <% end %>
          <p class="navbar-text pull-right">
            <% if user_signed_in? %>
                Logged in as <strong><%= current_user.email %></strong>.
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                <%= link_to "Logout", destroy_user_session_path, :method => :delete, :id => "Logout", :class => 'navbar-link'  %>
            <% else %>
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> |
            <% end %>
          </p>
          <% if user_signed_in? %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to 'Courses', courses_path %></li>
              <li><%= link_to 'Subjects', subjects_path %></li>
              <li><%= link_to 'SubjectToCourse', course_subjects_path %></li>
              <li><%= link_to 'Chapters', chapters_path %></li>
              <li><%= link_to 'Admission', admin_users_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span1"></div>
          <div class="span9">
            <%#= bootstrap_flash %>
            <%= render partial: "shared/flash_messages", flash: flash %>
            <%= yield %>
          </div>
          <div class="span2">
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>